### ISSUE TITLE
Improvements for YunoHost's package linter and continuous integration tests

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/komga_ynh#3]
I saw your PR over at https://github.com/YunoHost/apps/pull/1087, thanks for your contribution!

If I may request some changes, which may come important for the continuous integration and package linter tests, you should:
- [x] Assign a LICENSE to your package
- [x] Put the actual license of Komga (`MIT`) in the `manifest.json`
- [x] `git mv check_process.default check_process` and tune it to your needs (you will find an explanation of its syntax over [there](https://github.com/YunoHost/package_check))

Cheers ! 🚀

**Comment by navanchauhan** [comment]
I believe my latest commit added the License in the package, I'll update the manifest.json as well as finally get down to configuring check_process

**Comment by navanchauhan** [comment]
I think I have filled it correctly
